
auth0:
  audience: oO6pfoTQAfxJmkUa5se1txos5liAbYZa
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-7panm366.auth0.com/.well-known/jwks.json
          issuer-uri: https://dev-7panm366.auth0.com/
